
---
- hosts: all
  user: vagrant
  sudo: yes
  vars:
  # created with:
  # python -c 'import crypt; print crypt.crypt("somepass", "$somesalt$")'
    password: $1$salty$zpQ5Qp3lt02niRfob7iIX1

  tasks:
    - name: Set user group
      group: name=mikhaili state=present
    - name: Set new user
      user:
        name=mikhaili
        password={{password}}
        state=present
        group=mikhaili
        groups="sudo"
        shell=/bin/bash

    - name: ensure required packages are installed (for jpy installation)
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - python-software-properties
        - python-pip
        - python-dev
        - python-pycurl

    - name: Add multiverse repos (required for virtualbox guest stuff)
      apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty multiverse' state=present

    - name: install system packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - xinit
        - git
        - x11-xserver-utils
        - fluxbox
        - unzip
        - terminator
        - virtualbox-guest-utils
        - virtualbox-guest-x11
        - virtualbox-guest-dkms


    - name: (Pip) install behave
      pip: name={{ item }}
      with_items:
        - nose
        - behave
