
---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: python-numpy
      apt: pkg=python-numpy state=installed update_cache=true

    - name: ensure required packages are installed for Java 7
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - python-software-properties
        - python-pip
        - python-dev
        - git
        - unzip

    - name: Add Java repository to sources
      action: apt_repository repo='ppa:webupd8team/java'
     
    - name: Autoaccept license for Java
      action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
     
    - name: Update APT package cache
      action: apt update_cache=yes
     
    - name: Install Java 7
      action: apt pkg=oracle-java7-installer state=latest install_recommends=yes
     
    - name: Set Java 7 Env
      action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes

    - name: download JPY
      shell: wget https://www.dropbox.com/s/qh27h1a9za0rn55/jpy-master.zip

    - name: extract JPY from archive
      unarchive: src=jpy-master.zip dest=/home/vagrant copy=no
     
    - name: install JPY
      shell: python setup.py install 
      environment:
          JAVA_HOME: /usr/lib/jvm/java-8-oracle
      args:
          chdir: jpy-master

    - name: copy Beam
      unarchive: src=beam-5.0.4.tar.gz dest=/home/vagrant

    - name: install beampy
      shell: python setup.py install
      environment:
          BEAM_HOME: /home/vagrant/beam-5.0
      args:
          chdir: /home/vagrant/beam-5.0/modules/beam-python-5.0.4/beampy
