
---
- hosts: all
  user: vagrant
  sudo: yes
  vars:
  # created with:
  # python -c 'import crypt; print crypt.crypt("somepass", "$somesalt$")'
    password: $1$salty$zpQ5Qp3lt02niRfob7iIX1 

  tasks:
    - name: Set new user
      user:
        name=mikhaili
        password={{password}}
        state=present
        group=mikhaili
        groups="sudo"


    - name: ensure required packages are installed for Java 7
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - python-software-properties
        - python-pip
        - python-dev
        - git
        - unzip

    - name: (Pip) install behave
      pip: name={{ item }}
      with_items:
        - nose
        - behave

    - name: Add Java repository to sources
      action: apt_repository repo='ppa:webupd8team/java'
     
    - name: Autoaccept license for Java
      action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
     
    - name: Update APT package cache
      action: apt update_cache=yes
     
    - name: Install Java 7
      action: apt pkg=oracle-java7-installer state=latest install_recommends=yes
     
    - name: Set Java 7 Env
      action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes

    - name: download JPY
      shell: wget https://www.dropbox.com/s/qh27h1a9za0rn55/jpy-master.zip -O /tmp/jpy-master.zip

    - name: extract JPY from archive
      shell: unzip /tmp/jpy-master.zip -d /home/vagrant

    - name: install JPY
      shell: python setup.py install 
      environment:
          JAVA_HOME: /usr/lib/jvm/java-7-oracle
      args:
          chdir: /home/vagrant/jpy-master

    - name: remove JPY installation files
      shell: rm -rf /home/vagrant/jpy-master

    - name: Retrieve Beam from Dropbox
      shell: wget https://www.dropbox.com/s/hzqwnict6xz44zk/beam-5.0.4.tar.gz -O /tmp/beam-5.0.4.tar.gz

    - name: Extract Beam
      shell: tar -zxvf /tmp/beam-5.0.4.tar.gz --directory=/home/vagrant

    - name: install beampy
      shell: python setup.py install
      environment:
          BEAM_HOME: /home/vagrant/beam-5.0
      args:
          chdir: /home/vagrant/beam-5.0/modules/beam-python-5.0.4/beampy

    - name: general useful packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - python-numpy
        - python-pyproj
